/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedTodosRouteImport } from './routes/_authed/todos'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedProfileRouteImport } from './routes/_authed/profile'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAiTtsRouteImport } from './routes/api/ai/tts'
import { Route as ApiAiTranscriptionRouteImport } from './routes/api/ai/transcription'
import { Route as ApiAiStructuredRouteImport } from './routes/api/ai/structured'
import { Route as ApiAiImageRouteImport } from './routes/api/ai/image'
import { Route as ApiAiChatRouteImport } from './routes/api/ai/chat'
import { Route as AuthedAiStructuredRouteImport } from './routes/_authed/ai/structured'
import { Route as AuthedAiImageRouteImport } from './routes/_authed/ai/image'
import { Route as AuthedAiChatRouteImport } from './routes/_authed/ai/chat'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedTodosRoute = AuthedTodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProfileRoute = AuthedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiTtsRoute = ApiAiTtsRouteImport.update({
  id: '/api/ai/tts',
  path: '/api/ai/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiTranscriptionRoute = ApiAiTranscriptionRouteImport.update({
  id: '/api/ai/transcription',
  path: '/api/ai/transcription',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiStructuredRoute = ApiAiStructuredRouteImport.update({
  id: '/api/ai/structured',
  path: '/api/ai/structured',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiImageRoute = ApiAiImageRouteImport.update({
  id: '/api/ai/image',
  path: '/api/ai/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai/chat',
  path: '/api/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAiStructuredRoute = AuthedAiStructuredRouteImport.update({
  id: '/ai/structured',
  path: '/ai/structured',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAiImageRoute = AuthedAiImageRouteImport.update({
  id: '/ai/image',
  path: '/ai/image',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAiChatRoute = AuthedAiChatRouteImport.update({
  id: '/ai/chat',
  path: '/ai/chat',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/profile': typeof AuthedProfileRoute
  '/settings': typeof AuthedSettingsRoute
  '/todos': typeof AuthedTodosRoute
  '/ai/chat': typeof AuthedAiChatRoute
  '/ai/image': typeof AuthedAiImageRoute
  '/ai/structured': typeof AuthedAiStructuredRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/image': typeof ApiAiImageRoute
  '/api/ai/structured': typeof ApiAiStructuredRoute
  '/api/ai/transcription': typeof ApiAiTranscriptionRoute
  '/api/ai/tts': typeof ApiAiTtsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/profile': typeof AuthedProfileRoute
  '/settings': typeof AuthedSettingsRoute
  '/todos': typeof AuthedTodosRoute
  '/ai/chat': typeof AuthedAiChatRoute
  '/ai/image': typeof AuthedAiImageRoute
  '/ai/structured': typeof AuthedAiStructuredRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/image': typeof ApiAiImageRoute
  '/api/ai/structured': typeof ApiAiStructuredRoute
  '/api/ai/transcription': typeof ApiAiTranscriptionRoute
  '/api/ai/tts': typeof ApiAiTtsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/profile': typeof AuthedProfileRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/todos': typeof AuthedTodosRoute
  '/_authed/ai/chat': typeof AuthedAiChatRoute
  '/_authed/ai/image': typeof AuthedAiImageRoute
  '/_authed/ai/structured': typeof AuthedAiStructuredRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/image': typeof ApiAiImageRoute
  '/api/ai/structured': typeof ApiAiStructuredRoute
  '/api/ai/transcription': typeof ApiAiTranscriptionRoute
  '/api/ai/tts': typeof ApiAiTtsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/signup'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/todos'
    | '/ai/chat'
    | '/ai/image'
    | '/ai/structured'
    | '/api/ai/chat'
    | '/api/ai/image'
    | '/api/ai/structured'
    | '/api/ai/transcription'
    | '/api/ai/tts'
    | '/api/auth/$'
    | '/api/trpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/signup'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/todos'
    | '/ai/chat'
    | '/ai/image'
    | '/ai/structured'
    | '/api/ai/chat'
    | '/api/ai/image'
    | '/api/ai/structured'
    | '/api/ai/transcription'
    | '/api/ai/tts'
    | '/api/auth/$'
    | '/api/trpc/$'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/signin'
    | '/signup'
    | '/_authed/dashboard'
    | '/_authed/profile'
    | '/_authed/settings'
    | '/_authed/todos'
    | '/_authed/ai/chat'
    | '/_authed/ai/image'
    | '/_authed/ai/structured'
    | '/api/ai/chat'
    | '/api/ai/image'
    | '/api/ai/structured'
    | '/api/ai/transcription'
    | '/api/ai/tts'
    | '/api/auth/$'
    | '/api/trpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
  ApiAiImageRoute: typeof ApiAiImageRoute
  ApiAiStructuredRoute: typeof ApiAiStructuredRoute
  ApiAiTranscriptionRoute: typeof ApiAiTranscriptionRoute
  ApiAiTtsRoute: typeof ApiAiTtsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/todos': {
      id: '/_authed/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof AuthedTodosRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/profile': {
      id: '/_authed/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthedProfileRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/tts': {
      id: '/api/ai/tts'
      path: '/api/ai/tts'
      fullPath: '/api/ai/tts'
      preLoaderRoute: typeof ApiAiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/transcription': {
      id: '/api/ai/transcription'
      path: '/api/ai/transcription'
      fullPath: '/api/ai/transcription'
      preLoaderRoute: typeof ApiAiTranscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/structured': {
      id: '/api/ai/structured'
      path: '/api/ai/structured'
      fullPath: '/api/ai/structured'
      preLoaderRoute: typeof ApiAiStructuredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/image': {
      id: '/api/ai/image'
      path: '/api/ai/image'
      fullPath: '/api/ai/image'
      preLoaderRoute: typeof ApiAiImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/chat': {
      id: '/api/ai/chat'
      path: '/api/ai/chat'
      fullPath: '/api/ai/chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/ai/structured': {
      id: '/_authed/ai/structured'
      path: '/ai/structured'
      fullPath: '/ai/structured'
      preLoaderRoute: typeof AuthedAiStructuredRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/ai/image': {
      id: '/_authed/ai/image'
      path: '/ai/image'
      fullPath: '/ai/image'
      preLoaderRoute: typeof AuthedAiImageRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/ai/chat': {
      id: '/_authed/ai/chat'
      path: '/ai/chat'
      fullPath: '/ai/chat'
      preLoaderRoute: typeof AuthedAiChatRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedProfileRoute: typeof AuthedProfileRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedTodosRoute: typeof AuthedTodosRoute
  AuthedAiChatRoute: typeof AuthedAiChatRoute
  AuthedAiImageRoute: typeof AuthedAiImageRoute
  AuthedAiStructuredRoute: typeof AuthedAiStructuredRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedProfileRoute: AuthedProfileRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedTodosRoute: AuthedTodosRoute,
  AuthedAiChatRoute: AuthedAiChatRoute,
  AuthedAiImageRoute: AuthedAiImageRoute,
  AuthedAiStructuredRoute: AuthedAiStructuredRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  ApiAiChatRoute: ApiAiChatRoute,
  ApiAiImageRoute: ApiAiImageRoute,
  ApiAiStructuredRoute: ApiAiStructuredRoute,
  ApiAiTranscriptionRoute: ApiAiTranscriptionRoute,
  ApiAiTtsRoute: ApiAiTtsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
