/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareTokenRouteImport } from './routes/share/$token'
import { Route as AuthedTodosRouteImport } from './routes/_authed/todos'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedProfileRouteImport } from './routes/_authed/profile'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedAuditLogRouteImport } from './routes/_authed/audit-log'
import { Route as AuthedWsIndexRouteImport } from './routes/_authed/ws/index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAiTtsRouteImport } from './routes/api/ai/tts'
import { Route as ApiAiTranscriptionRouteImport } from './routes/api/ai/transcription'
import { Route as ApiAiStructuredRouteImport } from './routes/api/ai/structured'
import { Route as ApiAiImageRouteImport } from './routes/api/ai/image'
import { Route as ApiAiChatRouteImport } from './routes/api/ai/chat'
import { Route as AuthedWsWorkCountsRouteImport } from './routes/_authed/ws/work-counts'
import { Route as AuthedWsWdcChartsRouteImport } from './routes/_authed/ws/wdc-charts'
import { Route as AuthedWsProcessChartsRouteImport } from './routes/_authed/ws/process-charts'
import { Route as AuthedAiStructuredRouteImport } from './routes/_authed/ai/structured'
import { Route as AuthedAiImageRouteImport } from './routes/_authed/ai/image'
import { Route as AuthedAiChatRouteImport } from './routes/_authed/ai/chat'
import { Route as AuthedWsUnitIdIndexRouteImport } from './routes/_authed/ws/$unitId/index'
import { Route as AuthedWsUnitIdWdcWdcIdRouteImport } from './routes/_authed/ws/$unitId/wdc/$wdcId'
import { Route as AuthedWsUnitIdWcWcIdRouteImport } from './routes/_authed/ws/$unitId/wc/$wcId'
import { Route as AuthedWsUnitIdPcPcIdRouteImport } from './routes/_authed/ws/$unitId/pc/$pcId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedTodosRoute = AuthedTodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProfileRoute = AuthedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAuditLogRoute = AuthedAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWsIndexRoute = AuthedWsIndexRouteImport.update({
  id: '/ws/',
  path: '/ws/',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiTtsRoute = ApiAiTtsRouteImport.update({
  id: '/api/ai/tts',
  path: '/api/ai/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiTranscriptionRoute = ApiAiTranscriptionRouteImport.update({
  id: '/api/ai/transcription',
  path: '/api/ai/transcription',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiStructuredRoute = ApiAiStructuredRouteImport.update({
  id: '/api/ai/structured',
  path: '/api/ai/structured',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiImageRoute = ApiAiImageRouteImport.update({
  id: '/api/ai/image',
  path: '/api/ai/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai/chat',
  path: '/api/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedWsWorkCountsRoute = AuthedWsWorkCountsRouteImport.update({
  id: '/ws/work-counts',
  path: '/ws/work-counts',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWsWdcChartsRoute = AuthedWsWdcChartsRouteImport.update({
  id: '/ws/wdc-charts',
  path: '/ws/wdc-charts',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWsProcessChartsRoute = AuthedWsProcessChartsRouteImport.update({
  id: '/ws/process-charts',
  path: '/ws/process-charts',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAiStructuredRoute = AuthedAiStructuredRouteImport.update({
  id: '/ai/structured',
  path: '/ai/structured',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAiImageRoute = AuthedAiImageRouteImport.update({
  id: '/ai/image',
  path: '/ai/image',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAiChatRoute = AuthedAiChatRouteImport.update({
  id: '/ai/chat',
  path: '/ai/chat',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWsUnitIdIndexRoute = AuthedWsUnitIdIndexRouteImport.update({
  id: '/ws/$unitId/',
  path: '/ws/$unitId/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWsUnitIdWdcWdcIdRoute = AuthedWsUnitIdWdcWdcIdRouteImport.update({
  id: '/ws/$unitId/wdc/$wdcId',
  path: '/ws/$unitId/wdc/$wdcId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWsUnitIdWcWcIdRoute = AuthedWsUnitIdWcWcIdRouteImport.update({
  id: '/ws/$unitId/wc/$wcId',
  path: '/ws/$unitId/wc/$wcId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWsUnitIdPcPcIdRoute = AuthedWsUnitIdPcPcIdRouteImport.update({
  id: '/ws/$unitId/pc/$pcId',
  path: '/ws/$unitId/pc/$pcId',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/audit-log': typeof AuthedAuditLogRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/profile': typeof AuthedProfileRoute
  '/settings': typeof AuthedSettingsRoute
  '/todos': typeof AuthedTodosRoute
  '/share/$token': typeof ShareTokenRoute
  '/ai/chat': typeof AuthedAiChatRoute
  '/ai/image': typeof AuthedAiImageRoute
  '/ai/structured': typeof AuthedAiStructuredRoute
  '/ws/process-charts': typeof AuthedWsProcessChartsRoute
  '/ws/wdc-charts': typeof AuthedWsWdcChartsRoute
  '/ws/work-counts': typeof AuthedWsWorkCountsRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/image': typeof ApiAiImageRoute
  '/api/ai/structured': typeof ApiAiStructuredRoute
  '/api/ai/transcription': typeof ApiAiTranscriptionRoute
  '/api/ai/tts': typeof ApiAiTtsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/ws/': typeof AuthedWsIndexRoute
  '/ws/$unitId/': typeof AuthedWsUnitIdIndexRoute
  '/ws/$unitId/pc/$pcId': typeof AuthedWsUnitIdPcPcIdRoute
  '/ws/$unitId/wc/$wcId': typeof AuthedWsUnitIdWcWcIdRoute
  '/ws/$unitId/wdc/$wdcId': typeof AuthedWsUnitIdWdcWdcIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/audit-log': typeof AuthedAuditLogRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/profile': typeof AuthedProfileRoute
  '/settings': typeof AuthedSettingsRoute
  '/todos': typeof AuthedTodosRoute
  '/share/$token': typeof ShareTokenRoute
  '/ai/chat': typeof AuthedAiChatRoute
  '/ai/image': typeof AuthedAiImageRoute
  '/ai/structured': typeof AuthedAiStructuredRoute
  '/ws/process-charts': typeof AuthedWsProcessChartsRoute
  '/ws/wdc-charts': typeof AuthedWsWdcChartsRoute
  '/ws/work-counts': typeof AuthedWsWorkCountsRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/image': typeof ApiAiImageRoute
  '/api/ai/structured': typeof ApiAiStructuredRoute
  '/api/ai/transcription': typeof ApiAiTranscriptionRoute
  '/api/ai/tts': typeof ApiAiTtsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/ws': typeof AuthedWsIndexRoute
  '/ws/$unitId': typeof AuthedWsUnitIdIndexRoute
  '/ws/$unitId/pc/$pcId': typeof AuthedWsUnitIdPcPcIdRoute
  '/ws/$unitId/wc/$wcId': typeof AuthedWsUnitIdWcWcIdRoute
  '/ws/$unitId/wdc/$wdcId': typeof AuthedWsUnitIdWdcWdcIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/_authed/audit-log': typeof AuthedAuditLogRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/profile': typeof AuthedProfileRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/todos': typeof AuthedTodosRoute
  '/share/$token': typeof ShareTokenRoute
  '/_authed/ai/chat': typeof AuthedAiChatRoute
  '/_authed/ai/image': typeof AuthedAiImageRoute
  '/_authed/ai/structured': typeof AuthedAiStructuredRoute
  '/_authed/ws/process-charts': typeof AuthedWsProcessChartsRoute
  '/_authed/ws/wdc-charts': typeof AuthedWsWdcChartsRoute
  '/_authed/ws/work-counts': typeof AuthedWsWorkCountsRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/image': typeof ApiAiImageRoute
  '/api/ai/structured': typeof ApiAiStructuredRoute
  '/api/ai/transcription': typeof ApiAiTranscriptionRoute
  '/api/ai/tts': typeof ApiAiTtsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/_authed/ws/': typeof AuthedWsIndexRoute
  '/_authed/ws/$unitId/': typeof AuthedWsUnitIdIndexRoute
  '/_authed/ws/$unitId/pc/$pcId': typeof AuthedWsUnitIdPcPcIdRoute
  '/_authed/ws/$unitId/wc/$wcId': typeof AuthedWsUnitIdWcWcIdRoute
  '/_authed/ws/$unitId/wdc/$wdcId': typeof AuthedWsUnitIdWdcWdcIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/signup'
    | '/audit-log'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/todos'
    | '/share/$token'
    | '/ai/chat'
    | '/ai/image'
    | '/ai/structured'
    | '/ws/process-charts'
    | '/ws/wdc-charts'
    | '/ws/work-counts'
    | '/api/ai/chat'
    | '/api/ai/image'
    | '/api/ai/structured'
    | '/api/ai/transcription'
    | '/api/ai/tts'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/ws/'
    | '/ws/$unitId/'
    | '/ws/$unitId/pc/$pcId'
    | '/ws/$unitId/wc/$wcId'
    | '/ws/$unitId/wdc/$wdcId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/signup'
    | '/audit-log'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/todos'
    | '/share/$token'
    | '/ai/chat'
    | '/ai/image'
    | '/ai/structured'
    | '/ws/process-charts'
    | '/ws/wdc-charts'
    | '/ws/work-counts'
    | '/api/ai/chat'
    | '/api/ai/image'
    | '/api/ai/structured'
    | '/api/ai/transcription'
    | '/api/ai/tts'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/ws'
    | '/ws/$unitId'
    | '/ws/$unitId/pc/$pcId'
    | '/ws/$unitId/wc/$wcId'
    | '/ws/$unitId/wdc/$wdcId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/signin'
    | '/signup'
    | '/_authed/audit-log'
    | '/_authed/dashboard'
    | '/_authed/profile'
    | '/_authed/settings'
    | '/_authed/todos'
    | '/share/$token'
    | '/_authed/ai/chat'
    | '/_authed/ai/image'
    | '/_authed/ai/structured'
    | '/_authed/ws/process-charts'
    | '/_authed/ws/wdc-charts'
    | '/_authed/ws/work-counts'
    | '/api/ai/chat'
    | '/api/ai/image'
    | '/api/ai/structured'
    | '/api/ai/transcription'
    | '/api/ai/tts'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/_authed/ws/'
    | '/_authed/ws/$unitId/'
    | '/_authed/ws/$unitId/pc/$pcId'
    | '/_authed/ws/$unitId/wc/$wcId'
    | '/_authed/ws/$unitId/wdc/$wdcId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  ShareTokenRoute: typeof ShareTokenRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
  ApiAiImageRoute: typeof ApiAiImageRoute
  ApiAiStructuredRoute: typeof ApiAiStructuredRoute
  ApiAiTranscriptionRoute: typeof ApiAiTranscriptionRoute
  ApiAiTtsRoute: typeof ApiAiTtsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/todos': {
      id: '/_authed/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof AuthedTodosRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/profile': {
      id: '/_authed/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthedProfileRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/audit-log': {
      id: '/_authed/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuthedAuditLogRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/ws/': {
      id: '/_authed/ws/'
      path: '/ws'
      fullPath: '/ws/'
      preLoaderRoute: typeof AuthedWsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/tts': {
      id: '/api/ai/tts'
      path: '/api/ai/tts'
      fullPath: '/api/ai/tts'
      preLoaderRoute: typeof ApiAiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/transcription': {
      id: '/api/ai/transcription'
      path: '/api/ai/transcription'
      fullPath: '/api/ai/transcription'
      preLoaderRoute: typeof ApiAiTranscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/structured': {
      id: '/api/ai/structured'
      path: '/api/ai/structured'
      fullPath: '/api/ai/structured'
      preLoaderRoute: typeof ApiAiStructuredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/image': {
      id: '/api/ai/image'
      path: '/api/ai/image'
      fullPath: '/api/ai/image'
      preLoaderRoute: typeof ApiAiImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/chat': {
      id: '/api/ai/chat'
      path: '/api/ai/chat'
      fullPath: '/api/ai/chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/ws/work-counts': {
      id: '/_authed/ws/work-counts'
      path: '/ws/work-counts'
      fullPath: '/ws/work-counts'
      preLoaderRoute: typeof AuthedWsWorkCountsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/ws/wdc-charts': {
      id: '/_authed/ws/wdc-charts'
      path: '/ws/wdc-charts'
      fullPath: '/ws/wdc-charts'
      preLoaderRoute: typeof AuthedWsWdcChartsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/ws/process-charts': {
      id: '/_authed/ws/process-charts'
      path: '/ws/process-charts'
      fullPath: '/ws/process-charts'
      preLoaderRoute: typeof AuthedWsProcessChartsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/ai/structured': {
      id: '/_authed/ai/structured'
      path: '/ai/structured'
      fullPath: '/ai/structured'
      preLoaderRoute: typeof AuthedAiStructuredRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/ai/image': {
      id: '/_authed/ai/image'
      path: '/ai/image'
      fullPath: '/ai/image'
      preLoaderRoute: typeof AuthedAiImageRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/ai/chat': {
      id: '/_authed/ai/chat'
      path: '/ai/chat'
      fullPath: '/ai/chat'
      preLoaderRoute: typeof AuthedAiChatRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/ws/$unitId/': {
      id: '/_authed/ws/$unitId/'
      path: '/ws/$unitId'
      fullPath: '/ws/$unitId/'
      preLoaderRoute: typeof AuthedWsUnitIdIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/ws/$unitId/wdc/$wdcId': {
      id: '/_authed/ws/$unitId/wdc/$wdcId'
      path: '/ws/$unitId/wdc/$wdcId'
      fullPath: '/ws/$unitId/wdc/$wdcId'
      preLoaderRoute: typeof AuthedWsUnitIdWdcWdcIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/ws/$unitId/wc/$wcId': {
      id: '/_authed/ws/$unitId/wc/$wcId'
      path: '/ws/$unitId/wc/$wcId'
      fullPath: '/ws/$unitId/wc/$wcId'
      preLoaderRoute: typeof AuthedWsUnitIdWcWcIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/ws/$unitId/pc/$pcId': {
      id: '/_authed/ws/$unitId/pc/$pcId'
      path: '/ws/$unitId/pc/$pcId'
      fullPath: '/ws/$unitId/pc/$pcId'
      preLoaderRoute: typeof AuthedWsUnitIdPcPcIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAuditLogRoute: typeof AuthedAuditLogRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedProfileRoute: typeof AuthedProfileRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedTodosRoute: typeof AuthedTodosRoute
  AuthedAiChatRoute: typeof AuthedAiChatRoute
  AuthedAiImageRoute: typeof AuthedAiImageRoute
  AuthedAiStructuredRoute: typeof AuthedAiStructuredRoute
  AuthedWsProcessChartsRoute: typeof AuthedWsProcessChartsRoute
  AuthedWsWdcChartsRoute: typeof AuthedWsWdcChartsRoute
  AuthedWsWorkCountsRoute: typeof AuthedWsWorkCountsRoute
  AuthedWsIndexRoute: typeof AuthedWsIndexRoute
  AuthedWsUnitIdIndexRoute: typeof AuthedWsUnitIdIndexRoute
  AuthedWsUnitIdPcPcIdRoute: typeof AuthedWsUnitIdPcPcIdRoute
  AuthedWsUnitIdWcWcIdRoute: typeof AuthedWsUnitIdWcWcIdRoute
  AuthedWsUnitIdWdcWdcIdRoute: typeof AuthedWsUnitIdWdcWdcIdRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAuditLogRoute: AuthedAuditLogRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedProfileRoute: AuthedProfileRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedTodosRoute: AuthedTodosRoute,
  AuthedAiChatRoute: AuthedAiChatRoute,
  AuthedAiImageRoute: AuthedAiImageRoute,
  AuthedAiStructuredRoute: AuthedAiStructuredRoute,
  AuthedWsProcessChartsRoute: AuthedWsProcessChartsRoute,
  AuthedWsWdcChartsRoute: AuthedWsWdcChartsRoute,
  AuthedWsWorkCountsRoute: AuthedWsWorkCountsRoute,
  AuthedWsIndexRoute: AuthedWsIndexRoute,
  AuthedWsUnitIdIndexRoute: AuthedWsUnitIdIndexRoute,
  AuthedWsUnitIdPcPcIdRoute: AuthedWsUnitIdPcPcIdRoute,
  AuthedWsUnitIdWcWcIdRoute: AuthedWsUnitIdWcWcIdRoute,
  AuthedWsUnitIdWdcWdcIdRoute: AuthedWsUnitIdWdcWdcIdRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  ShareTokenRoute: ShareTokenRoute,
  ApiAiChatRoute: ApiAiChatRoute,
  ApiAiImageRoute: ApiAiImageRoute,
  ApiAiStructuredRoute: ApiAiStructuredRoute,
  ApiAiTranscriptionRoute: ApiAiTranscriptionRoute,
  ApiAiTtsRoute: ApiAiTtsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
